TILED2SATURN:= tiled2saturn

TILED2SATURN_CFLAGS_shared:= -I$(YAUL_INSTALL_ROOT)/$(YAUL_ARCH_SH_PREFIX)/include/tiled2saturn

TILED2SATURN_CFLAGS:= $(TILED2SATURN_CFLAGS_shared)
TILED2SATURN_CXXFLAGS:= $(TILED2SATURN_CFLAGS_shared)

TILED2SATURN_LDFLAGS:= -ltiled2saturn